# Generated by Django 5.0 on 2025-06-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
