# Generated by Django 5.0 on 2025-06-16 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0002_alter_staffmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofilemodel',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='human_resource.staffmodel'),
        ),
    ]
