# Generated by Django 5.0 on 2025-06-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0003_alter_staffprofilemodel_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='crate_target_for_bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
