# Generated by Django 5.0 on 2025-06-16 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_staffsalarypaymentmodel_options_and_more'),
        ('human_resource', '0002_alter_staffmodel_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('staff_to_cash', 'Staff to Office Cash'), ('staff_to_bank', 'Staff to Bank'), ('cash_to_bank', 'Office Cash to Bank'), ('bank_to_cash', 'Bank to Office Cash'), ('adjustment', 'Bank Balance Adjustment')], max_length=30)),
                ('source', models.CharField(choices=[('staff', 'Staff'), ('cash', 'Office Cash'), ('bank', 'Bank')], max_length=10)),
                ('destination', models.CharField(choices=[('staff', 'Staff'), ('cash', 'Office Cash'), ('bank', 'Bank')], max_length=10)),
                ('amount', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel')),
            ],
        ),
    ]
