# Generated by Django 5.0 on 2025-06-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_cashtransfermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransfermodel',
            name='transfer_type',
            field=models.CharField(choices=[('staff_to_cash', 'Staff to Office Cash'), ('staff_to_bank', 'Staff to Bank'), ('cash_to_bank', 'Office Cash to Bank'), ('bank_to_cash', 'Bank to Office Cash'), ('adjustment_add', 'Bank Balance Adjustment - Add'), ('adjustment_subtract', 'Bank Balance Adjustment - Substact')], max_length=30),
        ),
    ]
