# Generated by Django 5.0 on 2025-06-16 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_cashtransfermodel_transfer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffsalarymodel',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
