# Generated by Django 5.0 on 2025-06-17 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_staffsalarymodel_salary'),
        ('inventory', '0015_alter_stockinmodel_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransfermodel',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.suppliermodel'),
        ),
        migrations.AlterField(
            model_name='cashtransfermodel',
            name='destination',
            field=models.CharField(choices=[('staff', 'Staff'), ('cash', 'Office Cash'), ('bank', 'Bank'), ('petty', 'Petty Cash'), ('supplier', 'Supplier')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cashtransfermodel',
            name='source',
            field=models.CharField(choices=[('staff', 'Staff'), ('cash', 'Office Cash'), ('bank', 'Bank'), ('petty', 'Petty Cash'), ('supplier', 'Supplier')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cashtransfermodel',
            name='transfer_type',
            field=models.CharField(choices=[('staff_to_cash', 'Staff to Office Cash'), ('staff_to_bank', 'Staff to Bank'), ('cash_to_bank', 'Office Cash to Bank'), ('bank_to_cash', 'Bank to Office Cash'), ('bank_to_petty', 'Bank to Petty Cash'), ('cash_to_petty', 'Office Cash to Petty Cash'), ('bank_to_supplier', 'Bank to Supplier'), ('cash_to_supplier', 'Office Cash to Supplier'), ('adjustment_add', 'Bank Balance Adjustment - Add'), ('adjustment_subtract', 'Bank Balance Adjustment - Subtract')], max_length=30),
        ),
    ]
