# Generated by Django 5.0 on 2025-06-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_cashtransfermodel_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsalarypaymentmodel',
            name='payment_source',
            field=models.CharField(choices=[('cash', 'CASH'), ('bank', 'BANK')], default='cash', max_length=10),
            preserve_default=False,
        ),
    ]
