# Generated by Django 5.0 on 2025-06-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_staffsalarypaymentmodel_payment_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffsalarypaymentmodel',
            name='payment_source',
        ),
        migrations.AddField(
            model_name='staffsalarysummarymodel',
            name='payment_source',
            field=models.CharField(choices=[('cash', 'CASH'), ('bank', 'BANK')], default='cash', max_length=10),
            preserve_default=False,
        ),
    ]
