# Generated by Django 5.0 on 2025-09-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_remove_staffsalarypaymentmodel_payment_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemodel',
            name='payment_source',
            field=models.CharField(choices=[('PETTY_CASH', 'Petty Cash'), ('ACCOUNT_BALANCE', 'Account Balance')], default='PETTY_CASH', max_length=20),
        ),
    ]
