# Generated by Django 5.0 on 2025-06-10 10:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('number_of_empty', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('quantity', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_level', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.categorymodel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.productmodel')),
            ],
            options={
                'verbose_name_plural': 'Price History',
                'ordering': ['-change_date'],
            },
        ),
        migrations.CreateModel(
            name='StockInModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('quantity_left', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('quantity_sold', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('quantity_stocked_out', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('unit_cost_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ins', to='inventory.productmodel')),
            ],
            options={
                'verbose_name': 'Stock In Record',
                'verbose_name_plural': 'Stock In Records',
                'ordering': ['-date_added', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockInSummaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('cancelled', 'CANCELLED'), ('completed', 'COMPLETED')], default='pending', max_length=15)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='The overall date of this stock-in summary.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this summary record was created.')),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member who created this summary.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel')),
                ('products', models.ManyToManyField(blank=True, help_text='Individual stock-in records included in this summary.', to='inventory.stockinmodel')),
            ],
            options={
                'verbose_name': 'Stock In Summary',
                'verbose_name_plural': 'Stock In Summaries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockOutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_removed', models.DecimalField(decimal_places=2, help_text='Quantity of product removed.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cost_of_removed_stock', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated cost of the stock removed based on costing method.', max_digits=10, null=True)),
                ('reason', models.TextField(help_text="Why was this stock removed (e.g., 'Damaged', 'Internal Use', 'Lost').")),
                ('date_removed', models.DateField(blank=True, default=django.utils.timezone.now, help_text='The date this stock was physically removed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member who recorded this stock out.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_outs', to='inventory.stockinmodel')),
            ],
            options={
                'verbose_name': 'Stock Out Record',
                'verbose_name_plural': 'Stock Out Records',
                'ordering': ['-date_removed', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, to='inventory.productmodel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
