# Generated by Django 5.0 on 2025-06-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinsummarymodel',
            name='is_tampered',
            field=models.BooleanField(default=False, help_text='Indicates if any stock from this summary has been affected by a sale or stock-out. Tampered summaries cannot be edited/deleted.'),
        ),
        migrations.AlterField(
            model_name='stockinsummarymodel',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED')], default='pending', help_text="Status of the stock-in. 'Pending' means not yet committed to inventory. 'Confirmed' means committed.", max_length=10),
        ),
    ]
