# Generated by Django 5.0 on 2025-06-10 19:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockinsummarymodel_is_tampered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinmodel',
            name='quantity_added',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
