# Generated by Django 5.0 on 2025-06-12 10:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockinmodel_quantity_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinmodel',
            name='unit_selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
    ]
