# Generated by Django 5.0 on 2025-06-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockinmodel_unit_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinsummarymodel',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED')], help_text="Status of the stock-in. 'Pending' means not yet committed to inventory. 'Confirmed' means committed.", max_length=10),
        ),
    ]
