# Generated by Django 5.0 on 2025-06-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_stockinsummarymodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockoutmodel',
            name='stock_out_empty',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
