# Generated by Django 5.0 on 2025-06-16 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stockinsummarymodel_payment_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliermodel',
            name='products',
        ),
        migrations.AddField(
            model_name='suppliermodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.categorymodel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SupplierWalletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_wallet', to='inventory.suppliermodel')),
            ],
        ),
    ]
