# Generated by Django 5.0 on 2025-06-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_suppliermodel_products_suppliermodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliermodel',
            name='balance',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='suppliermodel',
            name='initial_balance',
            field=models.FloatField(blank=True, default=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SupplierWalletModel',
        ),
    ]
