# Generated by Django 5.0 on 2025-06-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_suppliermodel_balance_suppliermodel_initial_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliermodel',
            name='initial_balance',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
