# Generated by Django 5.0 on 2025-06-17 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_suppliermodel_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinmodel',
            name='date_added',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
