# Generated by Django 5.0 on 2025-06-17 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_stockinmodel_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinsummarymodel',
            name='payment_source',
        ),
        migrations.AddField(
            model_name='stockinsummarymodel',
            name='empty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockinsummarymodel',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.suppliermodel'),
        ),
        migrations.CreateModel(
            name='SupplierCashFlowHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('initial_amount', models.FloatField()),
                ('amount', models.FloatField()),
                ('final_amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.suppliermodel')),
            ],
            options={
                'verbose_name_plural': 'Supplier Balance History',
                'ordering': ['-date'],
            },
        ),
    ]
