# Generated by Django 5.0 on 2025-06-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_stockinsummarymodel_payment_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinsummarymodel',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
