# Generated by Django 3.2.20 on 2025-06-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_productmodel_initial_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='type',
            field=models.CharField(choices=[('bottle', 'BOTTLE'), ('can', 'CAN')], default='bottle', max_length=10),
        ),
        migrations.AddField(
            model_name='stockinsummarymodel',
            name='total_empty',
            field=models.IntegerField(default=0),
        ),
    ]
