# Generated by Django 5.2.4 on 2025-07-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20250630_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emptyadjustmentmodel',
            name='reason',
            field=models.CharField(choices=[('purchase', 'New Purchase'), ('theft', 'Theft'), ('correction', 'Correction'), ('damage', 'Damage'), ('other', 'Other')], max_length=20),
        ),
    ]
