# Generated by Django 5.2.4 on 2025-07-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_emptyadjustmentmodel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='price_for_empty',
            field=models.FloatField(default=1000),
        ),
    ]
