# Generated by Django 5.0 on 2025-06-14 17:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0002_alter_staffmodel_email'),
        ('inventory', '0006_stockoutmodel_stock_out_empty'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='returnmodel',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='salemodel',
            name='total_items',
        ),
        migrations.AddField(
            model_name='returnmodel',
            name='sale_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='returns_for_item', to='sale.saleitemmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitemmodel',
            name='crate_brought',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='saleitemmodel',
            name='crate_debt',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salemodel',
            name='delivery_status',
            field=models.CharField(choices=[('self', 'Self Collected'), ('driver', 'Delivered by Driver'), ('pending', 'Pending Delivery')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='salemodel',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='salemodel',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('partial', 'Partial'), ('complete', 'Complete')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='salemodel',
            name='total_amount_left',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='salemodel',
            name='total_amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='salemodel',
            name='total_crate_debt',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Total crates customer owes for this sale.', max_digits=10),
        ),
        migrations.AddField(
            model_name='salemodel',
            name='total_crates_brought',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total empty crates customer brought for this sale.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='returnmodel',
            name='quantity_returned',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='saleitemmodel',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='saleitemmodel',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sale.salemodel'),
        ),
        migrations.AlterField(
            model_name='saleitemmodel',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerWalletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_debt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('initial_debt_payment', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_wallet', to='sale.customermodel')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCrateDebtModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.categorymodel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crate_debts', to='sale.customermodel')),
            ],
            options={
                'verbose_name': 'Customer Crate Debt',
                'verbose_name_plural': 'Customer Crate Debts',
                'unique_together': {('customer', 'category')},
            },
        ),
    ]
