# Generated by Django 5.0 on 2025-06-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_remove_returnmodel_product_remove_returnmodel_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemodel',
            name='delivery_status',
            field=models.CharField(choices=[('self', 'Self Collected'), ('driver', 'Delivered by Driver')], max_length=20),
        ),
    ]
