# Generated by Django 5.0 on 2025-06-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_alter_salemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemodel',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
