# Generated by Django 5.0 on 2025-06-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_alter_salemodel_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemodel',
            name='payment_destination',
            field=models.CharField(blank=True, choices=[('bank', 'Paid To Driver'), ('cash', 'Paid Cash'), ('driver', 'Paid to Bank')], max_length=20),
        ),
    ]
