# Generated by Django 5.0 on 2025-06-18 12:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_productmodel_initial_quantity_and_more'),
        ('sale', '0007_salemodel_payment_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitemmodel',
            name='crate_brought',
        ),
        migrations.RemoveField(
            model_name='saleitemmodel',
            name='crate_debt',
        ),
        migrations.RemoveField(
            model_name='salemodel',
            name='total_crate_debt',
        ),
        migrations.RemoveField(
            model_name='salemodel',
            name='total_crates_brought',
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='payment_destination',
            field=models.CharField(blank=True, choices=[('bank', 'Paid to Bank'), ('cash', 'Paid Cash'), ('driver', 'Paid to Driver')], max_length=20),
        ),
        migrations.CreateModel(
            name='SaleCategoryEmpty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empty_expected', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('empty_brought', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('empty_owed', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.categorymodel')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_empties', to='sale.salemodel')),
            ],
            options={
                'verbose_name': 'Sale Category Crate Record',
                'verbose_name_plural': 'Sale Category Crate Records',
                'unique_together': {('sale', 'category')},
            },
        ),
    ]
