# Generated by Django 5.0 on 2025-06-18 19:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_productmodel_initial_quantity_and_more'),
        ('sale', '0008_remove_saleitemmodel_crate_brought_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitemmodel',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockinmodel'),
        ),
        migrations.AddField(
            model_name='saleitemmodel',
            name='total_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitemmodel',
            name='unit_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='salemodel',
            name='total_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Total discount across all sale items.', max_digits=10),
        ),
    ]
