# Generated by Django 5.0 on 2025-06-19 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0004_staffmodel_crate_target_for_bonus'),
        ('sale', '0010_alter_customercratedebtmodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercratedebtmodel',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
    ]
