# Generated by Django 5.0 on 2025-06-19 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0004_staffmodel_crate_target_for_bonus'),
        ('sale', '0011_customercratedebtmodel_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercratedebtmodel',
            name='driver',
        ),
        migrations.AddField(
            model_name='customerdebtrepaymentmodel',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
    ]
