# Generated by Django 5.0 on 2025-06-21 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0012_remove_customercratedebtmodel_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salecategoryempty',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salecategoryempty', to='sale.salemodel'),
        ),
    ]
