# Generated by Django 5.0 on 2025-06-21 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0013_alter_salecategoryempty_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salecategoryempty',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_empties', to='sale.salemodel'),
        ),
    ]
