# Generated by Django 5.0 on 2025-06-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0014_alter_salecategoryempty_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercratereturnmodel',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customercratereturnmodel',
            name='return_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('empty', 'Empty')], default='empty', max_length=10),
        ),
    ]
