# Generated by Django 5.2.3 on 2025-06-23 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0004_staffmodel_crate_target_for_bonus'),
        ('sale', '0014_alter_salecategoryempty_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercratereturnmodel',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customercratereturnmodel',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='customercratereturnmodel',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank'), ('driver', 'Driver')], default='cash', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customercratereturnmodel',
            name='return_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('empty', 'Empty')], default='empty', max_length=10),
        ),
    ]
