# Generated by Django 5.0 on 2025-06-23 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0004_staffmodel_crate_target_for_bonus'),
        ('sale', '0015_customercratereturnmodel_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercratereturnmodel',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='customercratereturnmodel',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank'), ('driver', 'Driver')], default='cash', max_length=20, null=True),
        ),
    ]
