# Generated by Django 5.0 on 2025-06-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('short_name', models.CharField(max_length=50)),
                ('logo', models.FileField(blank=True, upload_to='images/logo')),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.FloatField()),
                ('allow_sale_discount', models.BooleanField(default=True)),
                ('default_reorder_level', models.IntegerField()),
                ('crate_target_for_bonus', models.IntegerField(blank=True, null=True)),
                ('bonus_amount_per_crate', models.FloatField(blank=True, null=True)),
                ('minimum_unit_profit', models.FloatField()),
                ('recommended_unit_profit', models.FloatField()),
            ],
        ),
    ]
