# Generated by Django 5.0 on 2025-06-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_sitesettingmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfomodel',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='images/logo'),
        ),
    ]
