# Generated by Django 5.0 on 2025-06-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_alter_siteinfomodel_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingmodel',
            name='max_category_crate_debt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sitesettingmodel',
            name='max_crate_debt',
            field=models.IntegerField(default=0),
        ),
    ]
