# Generated by Django 5.0 on 2025-06-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_sitesettingmodel_max_category_crate_debt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingmodel',
            name='max_customer_debt',
            field=models.IntegerField(default=0),
        ),
    ]
