# Generated by Django 5.0 on 2025-06-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0005_sitesettingmodel_max_customer_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingmodel',
            name='opening_cash_balance',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
