# Generated by Django 5.0 on 2025-06-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0007_activitylogmodel_customer_activitylogmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingmodel',
            name='balance',
            field=models.FloatField(blank=True, default=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettingmodel',
            name='cash_balance',
            field=models.FloatField(blank=True, default=5000),
            preserve_default=False,
        ),
    ]
