# Generated by Django 5.0 on 2025-06-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0008_sitesettingmodel_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogmodel',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
