# Generated by Django 5.0 on 2025-06-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0009_activitylogmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingmodel',
            name='opening_petty_balance',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettingmodel',
            name='petty_balance',
            field=models.FloatField(blank=True, default=1000),
            preserve_default=False,
        ),
    ]
