# Generated by Django 5.0 on 2025-06-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0010_sitesettingmodel_opening_petty_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingmodel',
            name='price_for_empty',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
