# Generated by Django 5.0 on 2025-06-16 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0011_sitesettingmodel_price_for_empty'),
        ('inventory', '0011_remove_suppliermodel_products_suppliermodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogmodel',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.suppliermodel'),
        ),
    ]
