# Generated by Django 5.0 on 2025-06-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0012_activitylogmodel_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogmodel',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
